import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { withApiMonitoring } from "../_shared/api-observability.ts";
import { notifyPaymentApproved } from "../_shared/payment-notification.ts";
const hash=async(value:string)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value.trim().toLowerCase())))).map(byte=>byte.toString(16).padStart(2,"0")).join("");
async function trackMetaPurchase(order:Record<string,any>,request?:Request){const pixel=Deno.env.get("META_CAPI_PIXEL_ID"),token=Deno.env.get("META_CAPI_ACCESS_TOKEN");if(!pixel||!token)return;const phone=String(order.buyer_phone??"").replace(/\D/g,"");const event={event_name:"Purchase",event_time:Math.floor(Date.now()/1000),event_id:`purchase_${order.id}`,action_source:"website",event_source_url:Deno.env.get("SITE_URL")??"",user_data:{...(phone?{ph:[await hash(`55${phone}`)]}:{}),...(request?{"client_ip_address":request.headers.get("x-forwarded-for")?.split(",")[0],"client_user_agent":request.headers.get("user-agent")}:{})},custom_data:{currency:"BRL",value:(Number(order.amount_cents??1990)/100),order_id:order.id}};try{await fetch(`https://graph.facebook.com/v22.0/${pixel}/events?access_token=${encodeURIComponent(token)}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({data:[event],...(Deno.env.get("META_CAPI_TEST_EVENT_CODE")?{test_event_code:Deno.env.get("META_CAPI_TEST_EVENT_CODE")}:{})})})}catch{}}

const headers={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};
const fail=(error:string,status=400)=>new Response(JSON.stringify({error}),{status,headers});
const normalize=(value:unknown)=>String(value??"").replace(/\D/g,"");
const acceptedAmount=(value:unknown,expectedCents:number)=>Math.abs(Number(value)-(expectedCents/100))<=1;

async function start(db:ReturnType<typeof createClient>,order:Record<string,any>){const apiKey=Deno.env.get("KIE_API_KEY"),secret=Deno.env.get("KIE_CALLBACK_SECRET");if(!apiKey||!secret||!order.lyric_text)throw new Error("A geração final ainda não foi configurada.");await db.from("orders").update({status:"generating"}).eq("id",order.id);const callback=`${Deno.env.get("SUPABASE_URL")}/functions/v1/kie-delivery-webhook?secret=${encodeURIComponent(secret)}`;const r=await fetch("https://api.kie.ai/api/v1/generate",{method:"POST",headers:{"content-type":"application/json",Authorization:`Bearer ${apiKey}`},body:JSON.stringify({customMode:true,instrumental:false,model:"V4",prompt:order.lyric_text,style:order.style,title:`Uma música para ${order.honoree}`,vocalGender:order.quiz_data?.voice_gender??"f",callBackUrl:callback})});const d=await r.json() as {data?:{taskId?:string}};if(!r.ok||!d.data?.taskId)throw new Error("Não foi possível iniciar a música.");await db.from("orders").update({kie_task_id:d.data.taskId}).eq("id",order.id)}

async function releaseOrGenerate(db:ReturnType<typeof createClient>,order:Record<string,any>){const raw=Array.isArray(order.quiz_data?.preview_audio_urls)?order.quiz_data.preview_audio_urls:[];const urls=[...new Set(raw.filter((url:unknown):url is string=>typeof url==="string"&&url.length>0))].slice(0,2);if(urls.length>=2){await db.from("orders").update({status:"ready",paid_at:new Date().toISOString(),music_url:urls[0],music_versions:urls}).eq("id",order.id);return}await db.from("orders").update({paid_at:new Date().toISOString()}).eq("id",order.id);await start(db,order)}

type Receipt={is_payment_proof:boolean;amount:number|null;date_time:string|null;payer_name:string|null;payer_tax_id:string|null;recipient_name:string|null;recipient_tax_id:string|null;recipient_pix_key:string|null;institution:string|null;transaction_id:string|null;description:string|null;is_legible:boolean;possible_fraud:boolean;notes:string|null};
const receiptSchema={type:"object",additionalProperties:false,properties:{is_payment_proof:{type:"boolean"},amount:{type:["number","null"]},date_time:{type:["string","null"]},payer_name:{type:["string","null"]},payer_tax_id:{type:["string","null"]},recipient_name:{type:["string","null"]},recipient_tax_id:{type:["string","null"]},recipient_pix_key:{type:["string","null"]},institution:{type:["string","null"]},transaction_id:{type:["string","null"]},description:{type:["string","null"]},is_legible:{type:"boolean"},possible_fraud:{type:"boolean"},notes:{type:["string","null"]}},required:["is_payment_proof","amount","date_time","payer_name","payer_tax_id","recipient_name","recipient_tax_id","recipient_pix_key","institution","transaction_id","description","is_legible","possible_fraud","notes"]};

Deno.serve((req)=>withApiMonitoring("verify-manual-receipt",req,async()=>{if(req.method==="OPTIONS")return new Response("ok",{headers});if(req.method!=="POST")return fail("Método não permitido.",405);try{const{orderId,fileData,fileName}=await req.json() as {orderId?:string;fileData?:string;fileName?:string};if(!orderId||!fileData||fileData.length>8_000_000)return fail("Envie um comprovante de até 6 MB.");const apiKey=Deno.env.get("OPENAI_API_KEY"),receiverKey=normalize(Deno.env.get("MANUAL_PIX_KEY"));if(!apiKey||!receiverKey)return fail("A conferência ainda não foi configurada.",503);const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);const{data:order,error}=await db.from("orders").select("*").eq("id",orderId).eq("delivery_mode","download").single();if(error||!order)return fail("Pedido não encontrado.",404);if(order.status!=="awaiting_payment")return fail("Este pedido já foi enviado para produção.",409);const isPdf=(fileName??"").toLowerCase().endsWith(".pdf");const content=[{type:"input_text",text:`Leia visualmente este comprovante de pagamento e extraia os campos no JSON. O recebedor correto usa a chave Pix ${receiverKey}, que pode aparecer com espaços, pontos, barra, hífen ou parcialmente mascarada. Não invente dados: use null quando não estiver visível. Marque possible_fraud somente se houver indício visual claro de edição, inconsistência ou simulação.`},isPdf?{type:"input_file",file_data:fileData,filename:fileName??"comprovante.pdf"}:{type:"input_image",image_url:fileData,detail:"high"}] as any;const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"content-type":"application/json",Authorization:`Bearer ${apiKey}`},body:JSON.stringify({model:"gpt-5.4-mini",reasoning:{effort:"low"},max_output_tokens:500,text:{format:{type:"json_schema",name:"pix_receipt",strict:true,schema:receiptSchema}},input:[{role:"user",content}]})});const d=await r.json() as {output_text?:string;error?:{message?:string}};if(!r.ok)throw new Error(d.error?.message??"Não foi possível analisar o comprovante.");let receipt:Receipt;try{receipt=JSON.parse(d.output_text??"")}catch{throw new Error("Não foi possível ler os dados do comprovante.")}const receiverMatches=[receipt.recipient_tax_id,receipt.recipient_pix_key].some(value=>normalize(value)===receiverKey);const approved=receipt.is_payment_proof&&receipt.is_legible&&!receipt.possible_fraud&&acceptedAmount(receipt.amount,Number(order.amount_cents))&&receiverMatches;if(!approved)return fail("Comprovante inválido. Envie um comprovante legível com o valor correto para a chave Pix informada.",422);await trackMetaPurchase(order,req);await notifyPaymentApproved(db,order);await releaseOrGenerate(db,order);return new Response(JSON.stringify({approved:true}),{headers});}catch(error){return fail(error instanceof Error?error.message:"Não foi possível conferir o comprovante.",500)}}));
