"use client";
import { useState } from "react";

type Form = { recipient: string; style: string; honoree: string; story: string; buyerName: string; phone: string };
const choices = ["Minha mãe", "Meu amor", "Meu pai", "Uma amizade", "Outra pessoa especial"];

export default function Home() {
  const [view, setView] = useState<"home" | "quiz" | "lyrics" | "contact" | "pix">("home");
  const [step, setStep] = useState(0);
  const [form, setForm] = useState<Form>({ recipient: "", style: "", honoree: "", story: "", buyerName: "", phone: "" });
  const [pix, setPix] = useState<{ qrCode: string; payload: string; expiresAt?: string }>();
  const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const set = (key: keyof Form, value: string) => setForm(data => ({ ...data, [key]: value }));
  const ready = step === 0 ? !!form.recipient : step === 1 ? !!form.style : step === 2 ? form.honoree.length > 1 : form.story.length > 15;
  async function generatePix() { setLoading(true); setError(""); try { const baseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL; const publishableKey = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ?? process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY; if (!baseUrl || !publishableKey) throw new Error("O checkout ainda não foi configurado."); const r = await fetch(`${baseUrl}/functions/v1/create-pix`, { method: "POST", headers: { "content-type": "application/json", apikey: publishableKey, Authorization: `Bearer ${publishableKey}` }, body: JSON.stringify({ recipient: form.recipient, style: form.style, name: form.honoree, story: form.story, buyerName: form.buyerName, buyerPhone: form.phone.replace(/\D/g, "") }) }); const d = await r.json() as { qrCode?: string; pixPayload?: string; expiresAt?: string; error?: string }; if (!r.ok || !d.qrCode || !d.pixPayload) throw new Error(d.error || "Não foi possível gerar o Pix."); setPix({ qrCode: d.qrCode, payload: d.pixPayload, expiresAt: d.expiresAt }); setView("pix"); } catch(e) { setError(e instanceof Error ? e.message : "Tente novamente."); } finally { setLoading(false); } }
  if (view === "home") return <main className="min-h-screen bg-[#17142e] p-6 text-white"><section className="mx-auto flex min-h-[90vh] max-w-4xl flex-col justify-center"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#f1b55d]">Canção Única</p><h1 className="mt-5 max-w-3xl font-[family-name:var(--font-playfair)] text-6xl leading-none md:text-8xl">Sua história merece virar canção.</h1><p className="mt-7 max-w-xl text-lg text-white/70">Crie uma letra personalizada, revise antes de pagar e receba as versões finais pelo WhatsApp.</p><button onClick={() => setView("quiz")} className="mt-9 w-fit rounded-2xl bg-[#f1b55d] px-7 py-5 font-bold text-[#17142e]">Criar minha música</button></section></main>;
  if (view === "quiz") { const fields = [<Pick key="1" title="Para quem é a canção?" options={choices} value={form.recipient} choose={v => set("recipient",v)} />, <Pick key="2" title="Qual estilo combina?" options={["Romântico", "Sertanejo", "Gospel", "MPB", "Pop acústico"]} value={form.style} choose={v => set("style",v)} />, <Input key="3" title="Nome da pessoa especial" value={form.honoree} change={v => set("honoree",v)} />, <Input key="4" title="Conte a história que vira letra" textarea value={form.story} change={v => set("story",v)} />]; return <main className="min-h-screen bg-[#17142e] p-6 text-white"><section className="mx-auto flex min-h-[90vh] max-w-xl flex-col justify-center"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#f1b55d]">Etapa {step+1} de 4</p>{fields[step]}<button disabled={!ready} onClick={() => step === 3 ? setView("lyrics") : setStep(step+1)} className="mt-8 rounded-2xl bg-[#f1b55d] px-6 py-5 font-bold text-[#17142e] disabled:opacity-40">Continuar</button><button onClick={() => step ? setStep(step-1) : setView("home")} className="mt-4 text-sm text-white/65">Voltar</button></section></main>; }
  if (view === "lyrics") return <main className="min-h-screen bg-[#17142e] p-6 text-white"><section className="mx-auto flex min-h-[90vh] max-w-xl flex-col justify-center"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#f1b55d]">Revise sua letra</p><h1 className="mt-4 font-[family-name:var(--font-playfair)] text-5xl">Para {form.honoree}</h1><article className="mt-8 rounded-3xl border border-white/15 bg-white/10 p-6 whitespace-pre-line leading-8">{`Para ${form.honoree}, eu transformei em canção\n${form.story}\n\nCom ${form.recipient.toLowerCase()} no coração,\numa história única em forma de emoção.`}</article><button onClick={() => setView("contact")} className="mt-7 w-full rounded-2xl bg-[#f1b55d] px-6 py-5 font-bold text-[#17142e]">Gostei, gerar meu Pix</button><button onClick={() => setView("quiz")} className="mt-4 w-full text-sm text-white/65">Quero alterar algo</button></section></main>;
  if (view === "contact") return <main className="min-h-screen bg-[#fffaf5] p-6"><section className="mx-auto max-w-xl py-14"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#6740a3]">Último passo</p><h1 className="mt-4 font-[family-name:var(--font-playfair)] text-5xl">Onde falamos com você?</h1><label className="mt-8 block font-bold">Seu nome</label><input value={form.buyerName} onChange={e=>set("buyerName",e.target.value)} className="mt-2 w-full rounded-xl border border-black/10 p-4" placeholder="Seu nome"/><label className="mt-5 block font-bold">WhatsApp</label><div className="mt-2 flex rounded-xl border border-black/10"><span className="bg-black/5 p-4 font-bold">+55</span><input value={form.phone} onChange={e=>set("phone",e.target.value.replace(/\D/g,"").slice(0,11))} className="min-w-0 flex-1 p-4" inputMode="numeric" placeholder="(11) 99999-9999"/></div><button disabled={loading || form.buyerName.length<2 || form.phone.length<10} onClick={generatePix} className="mt-7 w-full rounded-2xl bg-[#3f2052] px-6 py-5 font-bold text-white disabled:opacity-40">{loading ? "Gerando…" : "Gerar Pix de R$ 39,90"}</button>{error && <p className="mt-4 text-red-700">{error}</p>}</section></main>;
  return <main className="min-h-screen bg-[#fffaf5] p-6"><section className="mx-auto max-w-xl py-10 text-center"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#6740a3]">Pix seguro</p><h1 className="mt-4 font-[family-name:var(--font-playfair)] text-5xl">Escaneie e confirme.</h1>{pix && <div className="mt-8 rounded-3xl bg-white p-6 shadow-xl"><img src={pix.qrCode} alt="QR Code Pix" className="mx-auto h-64 w-64"/><button onClick={()=>navigator.clipboard.writeText(pix.payload)} className="mt-6 w-full rounded-2xl bg-[#3f2052] p-4 font-bold text-white">Copiar código Pix</button><p className="mt-5 text-sm text-[#625b6d]">Após a confirmação, sua música entra em preparação e você recebe contato pelo WhatsApp.</p></div>}</section></main>;
}
function Pick({title,options,value,choose}:{title:string;options:string[];value:string;choose:(v:string)=>void}) { return <><h1 className="mt-5 font-[family-name:var(--font-playfair)] text-5xl">{title}</h1><div className="mt-8 grid gap-3">{options.map(x=><button key={x} onClick={()=>choose(x)} className={`rounded-2xl border p-5 text-left ${value===x?"border-[#f1b55d] bg-[#f1b55d]/15":"border-white/15"}`}>{x}</button>)}</div></>; }
function Input({title,value,change,textarea}:{title:string;value:string;change:(v:string)=>void;textarea?:boolean}) { return <><h1 className="mt-5 font-[family-name:var(--font-playfair)] text-5xl">{title}</h1>{textarea?<textarea value={value} onChange={e=>change(e.target.value)} className="mt-8 min-h-48 w-full rounded-2xl border border-white/15 bg-white/10 p-5"/>:<input value={value} onChange={e=>change(e.target.value)} className="mt-8 w-full rounded-2xl border border-white/15 bg-white/10 p-5"/>}</>; }
