"use client";
import { useState } from "react";

type Form = { recipient: string; style: string; honoree: string; story: string; buyerName: string; phone: string };
const recipients = ["Minha mãe", "Meu amor", "Meu pai", "Uma amizade", "Outra pessoa especial"];
const styles = ["Romântico", "Sertanejo", "Gospel", "MPB", "Pop acústico"];
const gallery = [
  ["Mãe", "https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=600&q=80"], ["Família", "https://images.unsplash.com/photo-1511895426328-dc8714191300?w=600&q=80"], ["Namorados", "https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?w=600&q=80"], ["Filho", "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=600&q=80"], ["Melhor amigo(a)", "https://images.unsplash.com/photo-1543807535-eceef0bc6599?w=600&q=80"], ["Para sempre", "https://images.unsplash.com/photo-1529634597503-139d3726fed5?w=600&q=80"]
];
const faqs = [["Quanto custa?", "Você recebe a prévia para avaliar e só então escolhe desbloquear as 2 versões por R$ 39,90."], ["Preciso pagar antes?", "Não. Primeiro você conta a história, confere a letra e decide se quer seguir para o Pix."], ["Como recebo minha música?", "Depois da confirmação do pagamento, preparamos as versões e avisamos você pelo WhatsApp."], ["Em quanto tempo fica pronta?", "A prévia é apresentada antes do pagamento. Depois, a produção final entra na nossa fila de preparação."], ["Quantas versões eu recebo?", "Duas versões completas, feitas a partir da sua história."]];

export default function Home() {
  const [view, setView] = useState<"landing" | "quiz" | "lyrics" | "contact" | "pix">("landing");
  const [step, setStep] = useState(0); const [openFaq, setOpenFaq] = useState<number | null>(0);
  const [form, setForm] = useState<Form>({ recipient: "", style: "", honoree: "", story: "", buyerName: "", phone: "" });
  const [pix, setPix] = useState<{ qrCode: string; payload: string; expiresAt?: string }>(); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const set = (key: keyof Form, value: string) => setForm(data => ({ ...data, [key]: value }));
  const start = () => { setView("quiz"); window.scrollTo({ top: 0, behavior: "smooth" }); };
  async function generatePix() { setLoading(true); setError(""); try { const baseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL; const publishableKey = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ?? process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY; if (!baseUrl || !publishableKey) throw new Error("O checkout ainda não foi configurado."); const r = await fetch(`${baseUrl}/functions/v1/create-pix`, { method: "POST", headers: { "content-type": "application/json", apikey: publishableKey, Authorization: `Bearer ${publishableKey}` }, body: JSON.stringify({ recipient: form.recipient, style: form.style, name: form.honoree, story: form.story, buyerName: form.buyerName, buyerPhone: form.phone.replace(/\D/g, "") }) }); const d = await r.json() as { qrCode?: string; pixPayload?: string; expiresAt?: string; error?: string }; if (!r.ok || !d.qrCode || !d.pixPayload) throw new Error(d.error || "Não foi possível gerar o Pix."); setPix({ qrCode: d.qrCode, payload: d.pixPayload, expiresAt: d.expiresAt }); setView("pix"); window.scrollTo({ top: 0, behavior: "smooth" }); } catch (e) { setError(e instanceof Error ? e.message : "Tente novamente."); } finally { setLoading(false); } }
  if (view !== "landing") return <Checkout view={view} form={form} step={step} setStep={setStep} set={set} setView={setView} generatePix={generatePix} loading={loading} error={error} pix={pix} />;
  return <main>
    <div className="offer-bar"><span>APROVEITE</span><b> SOMENTE HOJE</b><span> OFERTA ESPECIAL • 2 versões por R$ 39,90</span></div>
    <section className="hero"><div className="hero-glow"/><div className="hero-content"><p className="eyebrow">FELICIDADE EM MÚSICA</p><h1>Transforme sua <i>história</i> em uma música inesquecível.</h1><p className="hero-lead">Um presente único para emocionar quem você ama — feito a partir das suas palavras.</p><button className="primary" onClick={start}>🎁 Criar minha música</button><small>Você só paga depois de conferir sua prévia.</small><p className="social-proof">★★★★★ &nbsp; Mais de 12.000 histórias transformadas em canção</p></div><div className="hero-photo"><video autoPlay muted loop playsInline poster="/og-felicidade.png"><source src="/media/hero.mp4" type="video/mp4"/></video></div></section>
    <section className="section samples"><p className="kicker">MODELOS REAIS</p><h2>Ouça o clima que podemos criar para a sua história</h2><p>Cada composição é única. Escolha a emoção que mais combina com a pessoa especial.</p><div className="sample-grid">{[["🕊️","Gospel","/media/gospel.mp3"],["🤠","Sertanejo","/media/sertanejo.mp3"],["🥁","Pagode","/media/pagode.mp3"]].map(([icon,name,src])=><article className="sample" key={name}><div><span>{icon}</span><p>Modelo</p><h3>{name}</h3></div><audio controls preload="none" aria-label={`Ouvir modelo ${name}`}><source src={src} type="audio/mpeg"/>Seu navegador não suporta áudio.</audio></article>)}</div></section>
    <section className="quote"><div className="quote-video"><video controls playsInline preload="metadata" poster="/og-felicidade.png"><source src="/media/depoimento-alessandra.mp4" type="video/mp4"/>Seu navegador não suporta vídeo.</video></div><div><p className="kicker">DEPOIMENTO REAL</p><h2>“A emoção dela valeu mais que qualquer presente.”</h2><p>Uma música não é só um áudio. É uma memória que pode ser ouvida de novo, sempre que der saudade.</p><b>— Alessandra, cliente Felicidade em Música</b></div></section>
    <section className="section comparison"><p className="kicker">UM PRESENTE QUE FICA</p><h2>Por que uma música vale mais que mil presentes?</h2><p>Presentes materiais acabam. Uma canção feita para alguém especial eterniza um momento.</p><div className="compare-grid"><article className="ordinary"><h3>Presentes comuns</h3><p>Roupas saem de moda.</p><p>Perfumes acabam.</p><p>Chocolates duram minutos.</p><p>Jantares viram lembrança.</p><b>Bonitos no momento. Esquecidos depois.</b></article><article className="special"><span>INESQUECÍVEL</span><h3>Uma música personalizada</h3><p><b>Eterna:</b> fica guardada para sempre.</p><p><b>Emocionante:</b> toca direto na alma.</p><p><b>Única:</b> conta uma história exclusiva.</p><p><b>Compartilhável:</b> emociona família e amigos.</p><strong>💖 O presente perfeito</strong></article></div><button className="primary" onClick={start}>🎁 Quero criar a minha</button><small>Você só paga depois de conferir sua prévia.</small></section>
    <section className="gallery-section"><p className="kicker">HISTÓRIAS QUE VIRARAM MÚSICA</p><div className="gallery">{gallery.map(([title,src])=><figure key={title}><img src={src} alt={title}/><figcaption>{title}</figcaption></figure>)}</div></section>
    <section className="section"><p className="kicker">PACOTE DISPONÍVEL</p><h2>Uma experiência para marcar para sempre</h2><p>Não entregamos somente áudio: transformamos detalhes da sua história em uma canção para emocionar.</p><article className="pricing"><div className="pricing-tag">OFERTA ESPECIAL</div><p>Experiência completa</p><h3>Pacote Premium</h3><div><s>R$ 147,00</s><strong>R$ 39,90</strong><small>Pagamento único</small></div><p className="bonus">🎁 Pague 1, leve 2 versões</p><ul><li>Composição completa e personalizada</li><li>Voz e produção profissional</li><li>2 versões da música</li><li>Prévia antes do pagamento</li><li>Arquivo para guardar para sempre</li></ul><button className="primary" onClick={start}>🎵 Criar minha música</button><small>Você só paga depois de conferir a prévia.</small></article></section>
    <section className="faq" id="duvidas"><p className="kicker">TIRE SUAS DÚVIDAS</p><h2>Tudo o que você precisa saber antes de pedir sua música</h2>{faqs.map(([question,answer],index)=><button className="faq-item" key={question} onClick={()=>setOpenFaq(openFaq===index?null:index)}><span><b>{question}</b>{openFaq===index&&<em>{answer}</em>}</span><strong>{openFaq===index?"−":"+"}</strong></button>)}</section>
    <footer>© 2026 Felicidade em Música · Transformando histórias em canções ❤️</footer>
    <button className="floating-cta" onClick={start}>🎵 Criar minha música</button>
  </main>;
}

function Checkout({view,form,step,setStep,set,setView,generatePix,loading,error,pix}:{view:string;form:Form;step:number;setStep:(n:number)=>void;set:(k:keyof Form,v:string)=>void;setView:(v:"landing"|"quiz"|"lyrics"|"contact"|"pix")=>void;generatePix:()=>void;loading:boolean;error:string;pix?:{qrCode:string;payload:string;expiresAt?:string}}) {
  const ready = step===0?!!form.recipient:step===1?!!form.style:step===2?form.honoree.length>1:form.story.length>15;
  if(view==="quiz"){const label=["Para quem é a canção?","Qual estilo combina mais?","Qual o nome da pessoa especial?","Conte a história que vira canção"][step]; return <main className="flow"><button className="brand-back" onClick={()=>setView("landing")}>← Felicidade em Música</button><p className="kicker">ETAPA {step+1} DE 4</p><h1>{label}</h1>{step===0&&<Choices items={recipients} value={form.recipient} choose={v=>set("recipient",v)}/>} {step===1&&<Choices items={styles} value={form.style} choose={v=>set("style",v)}/>} {step===2&&<input autoFocus value={form.honoree} onChange={e=>set("honoree",e.target.value)} placeholder="Ex.: Maria"/>}{step===3&&<textarea autoFocus value={form.story} onChange={e=>set("story",e.target.value)} placeholder="Conte momentos, apelidos, sentimentos e tudo que não pode faltar..."/>}<button className="primary" disabled={!ready} onClick={()=>step===3?setView("lyrics"):setStep(step+1)}>Continuar</button><button className="text-button" onClick={()=>step?setStep(step-1):setView("landing")}>Voltar</button></main>}
  if(view==="lyrics")return <main className="flow"><button className="brand-back" onClick={()=>setView("landing")}>← Felicidade em Música</button><p className="kicker">SUA PRÉVIA</p><h1>Uma canção para {form.honoree}</h1><article className="lyric">{`Para ${form.honoree}, eu transformei em canção\n${form.story}\n\nCom ${form.recipient.toLowerCase()} no coração,\numa história única em forma de emoção.`}</article><button className="primary" onClick={()=>setView("contact")}>Gostei, gerar meu Pix</button><button className="text-button" onClick={()=>setView("quiz")}>Quero alterar algo</button></main>;
  if(view==="contact")return <main className="flow light"><button className="brand-back" onClick={()=>setView("landing")}>← Felicidade em Música</button><p className="kicker">ÚLTIMO PASSO</p><h1>Para onde enviamos sua música?</h1><label>Seu nome<input value={form.buyerName} onChange={e=>set("buyerName",e.target.value)} placeholder="Seu nome"/></label><label>WhatsApp<div className="phone"><b>+55</b><input value={form.phone} onChange={e=>set("phone",e.target.value.replace(/\D/g,"").slice(0,11))} inputMode="numeric" placeholder="(11) 99999-9999"/></div></label><button className="primary" disabled={loading||form.buyerName.length<2||form.phone.length<10} onClick={generatePix}>{loading?"Gerando Pix…":"Gerar Pix de R$ 39,90"}</button>{error&&<p className="error">{error}</p>}</main>;
  return <main className="flow light center"><p className="kicker">PAGAMENTO SEGURO</p><h1>Escaneie e confirme seu Pix.</h1>{pix&&<article className="pix-card"><img src={pix.qrCode} alt="QR Code Pix"/><button className="primary" onClick={()=>navigator.clipboard.writeText(pix.payload)}>Copiar código Pix</button><p>Assim que o pagamento for confirmado, sua música entra em preparação. Vamos falar com você pelo WhatsApp.</p></article>}</main>;
}
function Choices({items,value,choose}:{items:string[];value:string;choose:(item:string)=>void}){return <div className="choices">{items.map(item=><button key={item} className={value===item?"selected":""} onClick={()=>choose(item)}>{item}<span>→</span></button>)}</div>}
