"use client";
import { useEffect, useState } from "react";
import { trackInitiateCheckout } from "./lib/analytics";
import { SupportWhatsApp } from "./components/SupportWhatsApp";

type Form = { recipient: string; style: string; voiceGender: "" | "m" | "f"; honoree: string; story: string; buyerName: string; phone: string };
const recipients = ["Meu amor", "Minha mãe", "Meu pai", "Uma amizade", "Outra pessoa especial"];
const styles = ["Romântico", "Sertanejo", "Gospel", "MPB", "Pop acústico", "Samba", "Pagode"];
const manualPixReceiver = process.env.NEXT_PUBLIC_MANUAL_PIX_RECEIVER ?? "PAULO VITOR MACEDO PAES CORTES LOPES";
const manualPixKey = process.env.NEXT_PUBLIC_MANUAL_PIX_KEY ?? "54382323000116";
const musicPrice = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(process.env.NEXT_PUBLIC_MUSIC_PRICE_CENTS ?? 1990) / 100);
const savedLyricKey = "fem:lyric-preview:v1";
type SavedLyric = { form: Form; lyrics: string; revisionUsed: boolean; createdAt: number };
const gallery = [
  ["Mãe", "https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=600&q=80"], ["Família", "https://images.unsplash.com/photo-1511895426328-dc8714191300?w=600&q=80"], ["Namorados", "https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?w=600&q=80"], ["Filho", "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=600&q=80"], ["Melhor amigo(a)", "https://images.unsplash.com/photo-1543807535-eceef0bc6599?w=600&q=80"], ["Para sempre", "https://images.unsplash.com/photo-1529634597503-139d3726fed5?w=600&q=80"]
];
const faqs = [["Quanto custa?", "Você recebe a prévia para avaliar e só então escolhe desbloquear as 2 versões por R$ 19,90."], ["Preciso pagar antes?", "Não. Primeiro você conta a história, confere a letra e decide se quer seguir para o Pix."], ["Como recebo minha música?", "Depois da confirmação do pagamento, preparamos as versões e avisamos você pelo WhatsApp."], ["Em quanto tempo fica pronta?", "A prévia é apresentada antes do pagamento. Depois, a produção final entra na nossa fila de preparação."], ["Quantas versões eu recebo?", "Duas versões completas, feitas a partir da sua história."]];

export default function Home({directDownload=false,manualPayment=false}:{directDownload?:boolean;manualPayment?:boolean}) {
  const [view, setView] = useState<"landing" | "quiz" | "lyrics" | "adjust" | "contact" | "pix">("landing");
  const [step, setStep] = useState(0); const [openFaq, setOpenFaq] = useState<number | null>(0);
  const [form, setForm] = useState<Form>({ recipient: "", style: "", voiceGender: "", honoree: "", story: "", buyerName: "", phone: "" });
  const [pix, setPix] = useState<{ orderId?:string; qrCode?: string; payload?: string; expiresAt?: string }>(); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [lyricText, setLyricText] = useState(""); const [adjustment, setAdjustment] = useState(""); const [revisionUsed, setRevisionUsed] = useState(false); const [receipt,setReceipt]=useState<File>(); const [savedLyric,setSavedLyric]=useState<SavedLyric>(); const [paymentApproved,setPaymentApproved]=useState(false);
  const set = (key: keyof Form, value: string) => setForm(data => ({ ...data, [key]: value }));
  useEffect(()=>{try{const raw=localStorage.getItem(savedLyricKey);if(!raw)return;const saved=JSON.parse(raw) as SavedLyric;if(Date.now()-saved.createdAt<86_400_000&&saved.lyrics)setSavedLyric(saved);else localStorage.removeItem(savedLyricKey)}catch{localStorage.removeItem(savedLyricKey)}},[]);
  useEffect(()=>{if(manualPayment||!pix?.orderId||paymentApproved)return;let active=true;const check=async()=>{try{const baseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL;const publishableKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!baseUrl||!publishableKey)return;const response=await fetch(`${baseUrl}/functions/v1/get-payment-status`,{method:"POST",headers:{"content-type":"application/json",apikey:publishableKey,Authorization:`Bearer ${publishableKey}`},body:JSON.stringify({orderId:pix.orderId})});const data=await response.json() as {status?:string};if(active&&["paid","generating","ready"].includes(data.status??""))setPaymentApproved(true)}catch{}};void check();const timer=window.setInterval(()=>void check(),3000);return()=>{active=false;window.clearInterval(timer)}},[pix?.orderId,manualPayment,paymentApproved]);
  useEffect(()=>{const handle=(event:MouseEvent)=>{const button=(event.target as Element | null)?.closest<HTMLButtonElement>("button");if(!button||button.textContent!=="Copiar código Pix")return;button.textContent="✓ Copiado!";button.classList.add("copied");window.setTimeout(()=>{button.textContent="Copiar código Pix";button.classList.remove("copied")},1800)};document.addEventListener("click",handle);return()=>document.removeEventListener("click",handle)},[]);
  const persistLyric=(saved:SavedLyric)=>{localStorage.setItem(savedLyricKey,JSON.stringify(saved));setSavedLyric(saved)};
  const start = () => { if(savedLyric){setForm(savedLyric.form);setLyricText(savedLyric.lyrics);setRevisionUsed(savedLyric.revisionUsed);setView("lyrics")}else setView("quiz"); window.scrollTo({ top: 0, behavior: "smooth" }); };
  async function generatePix() { setLoading(true); setError(""); try { const baseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL; const publishableKey = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ?? process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY; if (!baseUrl || !publishableKey) throw new Error("O checkout ainda não foi configurado."); const endpoint=manualPayment?"create-manual-pix-order":"create-pix"; const r = await fetch(`${baseUrl}/functions/v1/${endpoint}`, { method: "POST", headers: { "content-type": "application/json", apikey: publishableKey, Authorization: `Bearer ${publishableKey}` }, body: JSON.stringify({ recipient: form.recipient, style: form.style, voiceGender: form.voiceGender, name: form.honoree, story: form.story, lyricText, buyerName: form.buyerName, buyerPhone: form.phone.replace(/\D/g, ""), deliveryMode: directDownload?"download":"whatsapp" }) }); const d = await r.json() as { orderId?:string; qrCode?: string; pixPayload?: string; expiresAt?: string; error?: string }; if (!r.ok || !d.orderId || (!manualPayment&&(!d.qrCode||!d.pixPayload))) throw new Error(d.error || "Não foi possível gerar o Pix."); trackInitiateCheckout(d.orderId); setPix({ orderId:d.orderId, qrCode: d.qrCode, payload: d.pixPayload, expiresAt: d.expiresAt }); setView("pix"); window.scrollTo({ top: 0, behavior: "smooth" }); } catch (e) { setError(e instanceof Error ? e.message : "Tente novamente."); } finally { setLoading(false); } }
  async function submitReceipt(){if(!receipt||!pix?.orderId)return;setLoading(true);setError("");try{const fileData=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(receipt)});const baseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL;const publishableKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!baseUrl||!publishableKey)throw new Error("O site ainda não foi configurado.");const r=await fetch(`${baseUrl}/functions/v1/verify-manual-receipt`,{method:"POST",headers:{"content-type":"application/json",apikey:publishableKey,Authorization:`Bearer ${publishableKey}`},body:JSON.stringify({orderId:pix.orderId,fileData,fileName:receipt.name})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Comprovante inválido.");setPaymentApproved(true)}catch(e){setError(e instanceof Error?e.message:"Comprovante inválido.")}finally{setLoading(false)}}
  async function generateLyrics() { setLoading(true); setError(""); try { const baseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL; const publishableKey = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ?? process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY; if (!baseUrl || !publishableKey) throw new Error("A prévia ainda não foi configurada."); const r = await fetch(`${baseUrl}/functions/v1/generate-lyrics`, { method: "POST", headers: { "content-type": "application/json", apikey: publishableKey, Authorization: `Bearer ${publishableKey}` }, body: JSON.stringify({ recipient: form.recipient, style: form.style, voiceGender: form.voiceGender, honoree: form.honoree, story: form.story }) }); const d = await r.json() as { lyrics?: string; error?: string }; if (!r.ok || !d.lyrics) throw new Error(d.error || "Não foi possível criar sua prévia."); persistLyric({form,lyrics:d.lyrics,revisionUsed:false,createdAt:Date.now()}); setLyricText(d.lyrics); setView("lyrics"); window.scrollTo({ top: 0, behavior: "smooth" }); } catch (e) { setError(e instanceof Error ? e.message : "Tente novamente."); } finally { setLoading(false); } }
  async function reviseLyrics() { setLoading(true); setError(""); try { const baseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL; const publishableKey = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ?? process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY; if (!baseUrl || !publishableKey) throw new Error("A revisão ainda não foi configurada."); const r = await fetch(`${baseUrl}/functions/v1/revise-lyrics`, { method: "POST", headers: { "content-type": "application/json", apikey: publishableKey, Authorization: `Bearer ${publishableKey}` }, body: JSON.stringify({ lyrics: lyricText, instruction: adjustment, honoree: form.honoree, style: form.style }) }); const d = await r.json() as { lyrics?: string; error?: string }; if (!r.ok || !d.lyrics) throw new Error(d.error || "Não foi possível alterar a letra."); persistLyric({form,lyrics:d.lyrics,revisionUsed:true,createdAt:Date.now()}); setLyricText(d.lyrics); setRevisionUsed(true); setAdjustment(""); } catch (e) { setError(e instanceof Error ? e.message : "Tente novamente."); } finally { setLoading(false); } }
  if (view !== "landing" && paymentApproved && manualPayment) return <ManualPaymentApproved orderId={pix?.orderId}/>;
  if (view !== "landing" && paymentApproved) return <PaymentApproved directDownload={directDownload} orderId={pix?.orderId}/>;
  if (view !== "landing" && manualPayment && view === "pix" && loading) return <ReceiptVerification/>;
  if (view !== "landing") return <Checkout view={view} form={form} step={step} setStep={setStep} set={set} setView={setView} generatePix={generatePix} generateLyrics={generateLyrics} lyricText={lyricText} loading={loading} error={error} pix={pix} adjustment={adjustment} setAdjustment={setAdjustment} revisionUsed={revisionUsed} reviseLyrics={reviseLyrics} directDownload={directDownload} manualPayment={manualPayment} receipt={receipt} setReceipt={setReceipt} submitReceipt={submitReceipt} />;
  return <main>
    <div className="offer-bar"><span>APROVEITE</span><b> SOMENTE HOJE</b><span> OFERTA ESPECIAL • 2 versões por R$ 19,90</span></div>
    <section className="hero"><div className="hero-glow"/><div className="hero-content"><p className="eyebrow">FELICIDADE EM MÚSICA</p><h1>Transforme sua <i>história</i> em uma música inesquecível.</h1><p className="hero-lead">Um presente único para emocionar quem você ama — feito a partir das suas palavras.</p><button className="primary" onClick={start}>🎁 Criar minha música</button><small>Você só paga depois de conferir sua prévia.</small><p className="social-proof">★★★★★ &nbsp; Mais de 12.000 histórias transformadas em canção</p></div><div className="hero-photo"><div className="hero-frame"><span className="hero-frame-label">feito da sua história</span><video autoPlay muted loop playsInline poster="/og-felicidade.png"><source src="/media/hero.mp4" type="video/mp4"/></video><span className="hero-frame-note">♫ uma lembrança para sempre</span></div></div></section>
    <section className="hero-after"><p>A próxima reação pode ser de alguém que você ama.</p><span>Conte a história. Nós transformamos em uma música única, criada especialmente para essa pessoa.</span></section>
    <section className="objection-break"><div className="objection-icon">♫</div><div><p className="kicker">É MAIS FÁCIL DO QUE PARECE</p><h2>Você conta a história. Nós transformamos em música.</h2><p>Não precisa saber escrever ou cantar. Basta compartilhar os momentos mais importantes, e criamos uma música personalizada para emocionar alguém especial.</p><strong>Você confere uma prévia antes de finalizar.</strong><button className="primary" onClick={start}>Criar minha música personalizada</button></div></section>
    <section className="section samples"><p className="kicker">MODELOS REAIS</p><h2>Ouça o clima que podemos criar para a sua história</h2><p>Cada composição é única. Escolha a emoção que mais combina com a pessoa especial.</p><div className="sample-grid">{[["🕊️","Gospel","/media/gospel.mp3"],["🤠","Sertanejo","/media/sertanejo.mp3"],["🥁","Pagode","/media/pagode.mp3"]].map(([icon,name,src])=><article className="sample" key={name}><div><span>{icon}</span><p>Modelo</p><h3>{name}</h3></div><audio controls preload="none" aria-label={`Ouvir modelo ${name}`}><source src={src} type="audio/mpeg"/>Seu navegador não suporta áudio.</audio></article>)}</div></section>
    <section className="quote"><div className="quote-video"><video controls playsInline preload="metadata" poster="/media/depoimento-alessandra-thumb.png"><source src="/media/depoimento-alessandra.mp4" type="video/mp4"/>Seu navegador não suporta vídeo.</video></div><div><p className="kicker">DEPOIMENTO REAL</p><h2>“A emoção dela valeu mais que qualquer presente.”</h2><p>Uma música não é só um áudio. É uma memória que pode ser ouvida de novo, sempre que der saudade.</p><b>— Alessandra, cliente Felicidade em Música</b></div></section>
    <section className="section comparison"><p className="kicker">UM PRESENTE QUE FICA</p><h2>Por que uma música vale mais que mil presentes?</h2><p>Presentes materiais acabam. Uma canção feita para alguém especial eterniza um momento.</p><div className="compare-grid"><article className="ordinary"><h3>Presentes comuns</h3><p>Roupas saem de moda.</p><p>Perfumes acabam.</p><p>Chocolates duram minutos.</p><p>Jantares viram lembrança.</p><b>Bonitos no momento. Esquecidos depois.</b></article><article className="special"><span>INESQUECÍVEL</span><h3>Uma música personalizada</h3><p><b>Eterna:</b> fica guardada para sempre.</p><p><b>Emocionante:</b> toca direto na alma.</p><p><b>Única:</b> conta uma história exclusiva.</p><p><b>Compartilhável:</b> emociona família e amigos.</p><strong>💖 O presente perfeito</strong></article></div><button className="primary" onClick={start}>🎁 Quero criar a minha</button><small>Você só paga depois de conferir sua prévia.</small></section>
    <section className="gallery-section"><p className="kicker">HISTÓRIAS QUE VIRARAM MÚSICA</p><div className="gallery">{gallery.map(([title,src])=><figure key={title}><img src={src} alt={title}/><figcaption>{title}</figcaption></figure>)}</div></section>
    <section className="section"><p className="kicker">PACOTE DISPONÍVEL</p><h2>Uma experiência para marcar para sempre</h2><p>Não entregamos somente áudio: transformamos detalhes da sua história em uma canção para emocionar.</p><article className="pricing"><div className="pricing-tag">OFERTA ESPECIAL</div><p>Experiência completa</p><h3>Pacote Premium</h3><div><s>R$ 147,00</s><strong>R$ 19,90</strong><small>Pagamento único</small></div><p className="bonus">🎁 Pague 1, leve 2 versões</p><ul><li>Composição completa e personalizada</li><li>Voz e produção profissional</li><li>2 versões da música</li><li>Prévia antes do pagamento</li><li>Arquivo para guardar para sempre</li></ul><button className="primary" onClick={start}>🎵 Criar minha música</button><small>Você só paga depois de conferir a prévia.</small></article></section>
    <section className="faq" id="duvidas"><p className="kicker">TIRE SUAS DÚVIDAS</p><h2>Tudo o que você precisa saber antes de pedir sua música</h2>{faqs.map(([question,answer],index)=><button className="faq-item" key={question} onClick={()=>setOpenFaq(openFaq===index?null:index)}><span><b>{question}</b>{openFaq===index&&<em>{answer}</em>}</span><strong>{openFaq===index?"−":"+"}</strong></button>)}</section>
    <SupportWhatsApp/>
    <footer>© 2026 Felicidade em Música · Transformando histórias em canções ❤️</footer>
  </main>;
}

function Checkout({view,form,step,setStep,set,setView,generatePix,generateLyrics,lyricText,loading,error,pix,adjustment,setAdjustment,revisionUsed,reviseLyrics,directDownload,manualPayment,receipt,setReceipt,submitReceipt}:{view:string;form:Form;step:number;setStep:(n:number)=>void;set:(k:keyof Form,v:string)=>void;setView:(v:"landing"|"quiz"|"lyrics"|"adjust"|"contact"|"pix")=>void;generatePix:()=>void;generateLyrics:()=>void;lyricText:string;loading:boolean;error:string;pix?:{orderId?:string;qrCode?:string;payload?:string;expiresAt?:string};adjustment:string;setAdjustment:(value:string)=>void;revisionUsed:boolean;reviseLyrics:()=>void;directDownload:boolean;manualPayment:boolean;receipt?:File;setReceipt:(file?:File)=>void;submitReceipt:()=>void}) {
  const ready = step===0?!!form.recipient:step===1?!!form.style:step===2?!!form.voiceGender:step===3?form.honoree.length>1:form.story.trim().split(/\s+/).filter(Boolean).length>=2;
  if(view==="quiz"){const label=["Para quem é a canção?","Qual estilo combina mais?","Qual voz combina mais com esta música?","Qual o nome da pessoa especial?","Conte a história que vira canção"][step]; return <main className={`flow ${step===3?"name-step":""}`}><button className="brand-back" onClick={()=>setView("landing")}>← Felicidade em Música</button><p className="kicker">ETAPA {step+1} DE 5</p><h1>{label}</h1>{step===0&&<Choices items={recipients} value={form.recipient} choose={v=>set("recipient",v)}/>} {step===1&&<Choices items={styles} value={form.style} choose={v=>set("style",v)}/>} {step===2&&<VoiceChoices value={form.voiceGender} choose={v=>set("voiceGender",v)}/>} {step===3&&<><p className="name-context">Quando ela ouvir o próprio nome na música, vai sentir que esse presente foi feito só para ela.</p><input autoFocus value={form.honoree} onChange={e=>set("honoree",e.target.value)} placeholder="Ex.: Maria" required/></>}{step===4&&<textarea autoFocus value={form.story} onChange={e=>set("story",e.target.value)} placeholder="Conte momentos, apelidos, sentimentos e tudo que não pode faltar..." required/>}{step===4&&loading&&<GenerationStatus/>}<button className="primary" disabled={!ready||loading} onClick={()=>step===4?generateLyrics():setStep(step+1)}>{step===4&&loading?"Criando sua prévia…":"Continuar"}</button>{error&&<p className="error">{error}</p>}<button className="text-button" onClick={()=>step?setStep(step-1):setView("landing")}>Voltar</button></main>}
  if(view==="lyrics")return <main className="flow preview-screen"><button className="brand-back" onClick={()=>setView("landing")}>← Felicidade em Música</button><p className="kicker">SUA PRÉVIA</p><h1>Uma canção para {form.honoree}</h1><article className="lyric">{lyricText}</article><div className="preview-actions"><button className="primary" onClick={()=>setView("contact")}>Continuar</button>{!revisionUsed&&<button className="secondary-button" onClick={()=>setView("adjust")}>Quero alterar algo</button>}</div>{error&&<p className="error">{error}</p>}</main>;
  if(view==="adjust")return <main className="flow adjust-screen"><button className="brand-back" onClick={()=>setView("lyrics")}>← Voltar para a prévia</button><p className="kicker">SUA ÚNICA ALTERAÇÃO</p><h1>Como você quer deixar essa música ainda mais especial?</h1><p className="adjust-copy">Conte o detalhe que não pode faltar: um apelido, uma lembrança, uma frase ou o sentimento que deseja reforçar.</p><textarea className="adjustment-box" autoFocus value={adjustment} onChange={event=>setAdjustment(event.target.value)} placeholder="Ex.: inclua nosso apelido e deixe o refrão mais alegre…"/><button className="primary" disabled={loading||!adjustment.trim()} onClick={reviseLyrics}>{loading?"Ajustando sua letra…":"Aplicar minha alteração"}</button>{error&&<p className="error">{error}</p>}</main>;
  if(view==="contact"&&manualPayment)return <main className="flow light manual-payment"><button className="brand-back" onClick={()=>setView("lyrics")}>← Voltar para a prévia</button><p className="kicker">PAGAMENTO PIX</p><h1>Desbloqueie sua música completa.</h1><div className="manual-price"><span>Valor único</span><strong>{musicPrice}</strong><small>Oferta válida somente hoje</small></div><div className="manual-recipient"><span>Nome do recebedor</span><b>{manualPixReceiver}</b><hr/><span>Chave Pix</span><code>{manualPixKey}</code></div><button className="primary manual-copy" onClick={event=>{navigator.clipboard.writeText(manualPixKey);const button=event.currentTarget;button.textContent="✓ Copiado!";button.classList.add("copied");setTimeout(()=>{void generatePix()},650)}}>⧉ Copiar chave Pix</button><p className="manual-security">◈ Pagamento seguro via Pix</p>{error&&<p className="error">{error}</p>}</main>;
  if(view==="contact")return <main className="flow light contact-step"><button className="brand-back" onClick={()=>setView("landing")}>← Felicidade em Música</button><p className="kicker">OFERTA RESERVADA PARA VOCÊ</p><h1>Gere o Pix para receber suas duas versões completas. {form.honoree} vai se encantar com essa surpresa!</h1><p className="contact-intro">Informe seu nome e WhatsApp para receber a entrega. O Pix é gerado exclusivamente para este pedido e expira em breve.</p><div className="contact-offer"><span>Condição especial por tempo limitado</span><strong><s>R$ 37,00</s> por R$ 19,90</strong><em>Pagamento único • 2 versões completas</em></div><label>Seu nome<input value={form.buyerName} onChange={e=>set("buyerName",e.target.value)} placeholder="Como você quer ser chamado?" required/></label><label>WhatsApp<div className="phone"><b>+55</b><input value={form.phone} onChange={e=>set("phone",e.target.value.replace(/\D/g,"").slice(0,11))} inputMode="numeric" placeholder="(11) 99999-9999" required/></div></label><button className="primary pix-action" disabled={loading||form.buyerName.length<2||form.phone.length<10} onClick={generatePix}>{loading?"Gerando Pix…":"Gerar Pix"}</button>{error&&<p className="error">{error}</p>}</main>;
  return <main className="flow light center"><p className="kicker">{manualPayment?"COMPROVANTE PIX":"PAGAMENTO SEGURO"}</p><h1>{manualPayment?"Envie seu comprovante.":"Escaneie e confirme seu Pix."}</h1>{pix&&<article className="pix-card">{manualPayment?<><p>Após o envio, conferimos o comprovante e começamos a gerar sua música.</p><label className="receipt-drop">⇧<b>{receipt?receipt.name:"Toque para enviar seu comprovante"}</b><span>Escolha uma foto da galeria, tire uma foto ou envie um PDF.</span><em>JPG &nbsp; PNG &nbsp; PDF</em><input type="file" accept="image/png,image/jpeg,application/pdf" onChange={event=>setReceipt(event.target.files?.[0])}/></label><button className="primary" disabled={!receipt||loading} onClick={submitReceipt}>{loading?"Conferindo comprovante…":"⇧ Enviar comprovante"}</button><button className="secondary-button manual-recopy" onClick={()=>navigator.clipboard.writeText(manualPixKey)}>⧉ Copiar chave Pix novamente</button>{error&&<p className="error">{error}</p>}</>:<><img src={pix.qrCode} alt="QR Code Pix"/><button className="primary" onClick={()=>navigator.clipboard.writeText(pix.payload??"")}>Copiar código Pix</button><p>{directDownload?"Após a confirmação, sua música será preparada e liberada para baixar nesta página.":"Assim que o pagamento for confirmado, sua música entra em preparação. Vamos falar com você pelo WhatsApp."}</p>{directDownload&&pix.orderId&&<a className="primary download-link" href={`/entrega?pedido=${pix.orderId}`}>Já paguei, acompanhar minha entrega</a>}</>}</article>}</main>;
}
function Choices({items,value,choose}:{items:string[];value:string;choose:(item:string)=>void}){return <div className="choices">{items.map(item=><button key={item} className={value===item?"selected":""} onClick={()=>choose(item)}>{item}<span>→</span></button>)}</div>}
function VoiceChoices({value,choose}:{value:""|"m"|"f";choose:(value:"m"|"f")=>void}){return <div className="choices"><button className={value==="f"?"selected":""} onClick={()=>choose("f")}>Voz feminina<span>→</span></button><button className={value==="m"?"selected":""} onClick={()=>choose("m")}>Voz masculina<span>→</span></button></div>}
function GenerationStatus(){return <div className="generation-status" role="status" aria-live="polite"><div className="generation-note"><span className="generation-note-dot"/><span className="generation-note-dot"/><span className="generation-note-dot"/></div><div><strong>Criando a sua prévia</strong><span>Transformando sua história em uma letra única.</span></div></div>}
function ReceiptVerification(){return <main className="flow v2-flow center music-loading receipt-verification" aria-live="polite"><p className="kicker">VERIFICANDO PAGAMENTO</p><div className="music-loading-note">⌕</div><p className="music-loading-phrase">Estamos conferindo seu comprovante Pix</p><h1>Só mais um instante.</h1><p className="v2-copy">Estamos verificando os dados do pagamento com segurança.</p><div className="music-progress receipt-progress"><span/></div></main>}
function ManualPaymentApproved({orderId}:{orderId?:string}){useEffect(()=>{if(!orderId)return;const timer=window.setTimeout(()=>{window.location.href=`/entrega?pedido=${orderId}`},1800);return()=>window.clearTimeout(timer)},[orderId]);return <main className="flow v2-flow center music-loading manual-production" aria-live="polite"><div className="payment-success-check" aria-hidden="true">✓</div><p className="kicker">PAGAMENTO APROVADO</p><p className="music-loading-phrase">Sua surpresa foi liberada</p><h1>Estamos produzindo as versões completas da sua música.</h1><p className="v2-copy">Aguarde nesta página. Em breve você poderá ouvir e baixar as duas versões completas.</p><div className="music-progress"><span/></div>{orderId&&<a className="secondary-button" href={`/entrega?pedido=${orderId}`}>Acompanhar produção</a>}</main>}
function PaymentApproved({directDownload,orderId}:{directDownload:boolean;orderId?:string}){useEffect(()=>{if(!directDownload||!orderId)return;const timer=window.setTimeout(()=>{window.location.href=`/entrega?pedido=${orderId}`},1800);return()=>window.clearTimeout(timer)},[directDownload,orderId]);return <main className="flow light center payment-success"><div className="payment-success-check" aria-hidden="true">✓</div><p className="kicker">PAGAMENTO APROVADO</p><h1>Pronto! Sua surpresa está a caminho.</h1><p>{directDownload?"Pagamento confirmado. Abrindo sua página de entrega…":"Recebemos seu pagamento e vamos chamar você agora mesmo no WhatsApp para continuar a preparação da sua música."}</p>{directDownload&&orderId&&<a className="primary download-link" href={`/entrega?pedido=${orderId}`}>Abrir entrega agora</a>}<SupportWhatsApp compact/></main>}
